repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0 # Use the ref you want to point at
    hooks:
        - id: trailing-whitespace
          types: [file, text]
        - id: check-docstring-first
        - id: check-case-conflict
        - id: end-of-file-fixer
          types: [python]
        - id: requirements-txt-fixer
        - id: mixed-line-ending
          types: [python]
          args: [--fix=no]
        - id: debug-statements
        - id: fix-byte-order-marker
        - id: check-yaml
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
        - id: black
          types: [python]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/pycqa/flake8.git
    rev: 7.0.0
    hooks:
        - id: flake8
          types: [python]
